services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
    container_name: django_backend
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done &&
            python Forum/manage.py migrate &&
            python Forum/manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=your_db_password
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./Backend:/app
       - ./Backend/Forum/static:/app/Forum/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./Frontend
    container_name: react_frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./Frontend/forum-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
